# Site settings
title: LUNCHMATES Blog
email: support@lunchmates.org
description: > # this means to ignore newlines until "baseurl:"
  Lunchmates.org blog. Find out more about Lunchmates and lunch roulette.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.lunchmates.org" # the base hostname & protocol for your site
twitter_username: lunch_mates
github_username:  lunchmates

# Build settings
markdown: kramdown
